### ISSUE TITLE
Django 1.8 compatibility

### ISSUE THREAD

**Issue by czpython** [joshourisman/django-tablib#52]
Hello,

Was wondering if a new release is coming with Django 1.8 compatibility from the develop branch?

**Comment by shanbady** [comment]
We are also curious about this.

**Comment by mkoistinen** [comment]
+1

**Comment by mrgix** [comment]
+1

**Comment by czpython** [comment]
Fixed in release 4cd6b8e52afdcbbdbadf33869c9ec3c21526beee
